# Find EGL
#
# EGL_INCLUDE_DIR
# EGL_LIBRARY

message("Custom FindEGL.cmake")
FIND_PATH(
    EGL_INCLUDE_DIR
    NAMES
        EGL/egl.h
)
FIND_LIBRARY(
    EGL_LIBRARY
    NAMES
        EGL
        libEGL
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
    EGL
    FOUND_VAR
        EGL_FOUND
    REQUIRED_VARS
        EGL_LIBRARY
)

MARK_AS_ADVANCED(EGL_INCLUDE_DIR)
MARK_AS_ADVANCED(EGL_LIBRARY)